### ISSUE TITLE
Integrating headless mode with scripts already using PySDL2?

### ISSUE THREAD

**Issue by a-hurst** [Baekalfen/PyBoy#107]
So I work in a cognitive science lab, and we've been talking about doing some studies looking at how differences in boredom proneness affect exploration and risk-taking behaviour using video game environments. Since it can be easily integrated with Python for automatic measuring and writing out data of interest, I've been looking at PyBoy as a framework for getting this off the ground.

*However*, PyBoy's Cython linking of SDL2 seems to make this a problem, since our in-house framework for writing cogsci experiments is based on PySDL2 and the ctypes linking of SDL2 seems to conflict with PyBoy's, causing a segfault when trying to fetch a Numpy array of the screen contents.

The main workarounds I can think of are:
1. Use multiprocessing to run PyBoy in a separate process and fetch screen contents/send input events over a pipe.
2. Modify PyBoy to compile in Cython without SDL2 for a headless-only build (is this possible, or does headless mode still rely on SDL2 for back-end stuff?)
3. Force PyBoy to run in non-Cython mode so both use PySDL2 and there isn't any linking conflict (assuming this would be much slower).

Given the PyBoy internals, any thoughts as to the best way to work around this issue? Thanks in advance!

**Comment by krs013** [comment]
Right now the headless option is probably the best. This already exists in PyBoy and works pretty well. Just start it up with `PyBoy(romfile, 'headless')`, and get the screen contents with one of the [available functions](https://docs.pyboy.dk/pyboy.html#pyboy.pyboy.PyBoy.get_raw_screen_buffer). You will have to write your own code for [sending input](https://docs.pyboy.dk/pyboy.html#pyboy.pyboy.PyBoy.send_input), though, or adapt what you find in `window_sdl2.py`. It doesn't call any SDL2 code that I can see, though it will still need PySDL2 to be available for import due to how it's structured.

In the future, PyBoy will undergo a change where the creation of the screen buffer and rendering to it is separated entirely from the SDL2 UI, so it will work like that but more naturally. That change is part of the focus of #100, but I wouldn't make any promises or predictions on when that'll be done. Core changes like that tend to require a lot of care. Either way, though, if you run it with the headless "window" your end of the code should be mostly the same.

OTOH, if you'd rather run PyBoy but only make some change to the window code or run your own stuff alongside it, you can run it under PyPy (your code would have to be running in PyPy as well). The performance is still sufficient to run at real time speeds on any modern machine, and all the Cython bits are automatically disabled.

**Comment by Baekalfen** [comment]
@a-hurst V1.0.0 has been released today with a brand new way of handling SDL2. Could you see if anything has changed? Otherwise, I'll try to do some more to accommodate your need.

**Comment by a-hurst** [comment]
@Baekalfen With PyBoy 1.0.0, I get a bunch of Objective-C warning messages on launch about there being multiple definitions of various SDL2 functions (I don't think this is avoidable on macOS when two different SDL libraries are dynamically linked within the same Python session, as I've encountered this before), but it no longer segfaults and now PyBoy runs smoothly within my experiment framework. Thanks so much for the fix!
