### ISSUE TITLE
Randomize first Tetromino

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#141]
When using the game_wrapper, the first Tetromino will always be the same.

Implement a function, which scrambles the registers and provides a new starting Tetromino at every call to `start_game` and `reset_game`.

**Comment by MathisFederico** [comment]
Maybe this sould be a parameter ? Or maybe we should add nome seed support ! For example if you want to do a competition, we would want the tetrominos to be the same in both games.

**Comment by naclander** [comment]
Is this because random RAM on startup [is not implemented](https://github.com/Baekalfen/PyBoy/blob/master/pyboy/core/ram.py#L20)?

**Comment by krs013** [comment]
It's more likely that the game starts after the same number of frames each time, but it could be the RAM. I can't find any info on how the Tetris randomizer is initialized, but I would bet that random RAM is not the fix necessary. Any game programmer at the time who relied on that behavior would risk their game breaking in the future, since random RAM contents was probably an undocumented feature that wasn't guaranteed in future hardware revisions.

**Comment by Baekalfen** [comment]
@naclander @krs013  Yes, partly. The timer DIV register is crucial to the random Tetromino. Because we don't randomize the value on startup, it start with the "seed" of 0, thereby being fully deterministic, if used in a script for example.
