### ISSUE TITLE
Operation key_Forced game termination

### ISSUE THREAD

**Issue by ghost** [Baekalfen/PyBoy#169]
The operation key is not explained, so when I found it myself, I pressed the ESC key, but the game was aborted and the Pi-Boy did not exit normally.
After checking, even if you press the X button to exit without pressing the ESC key, you cannot exit normally.

I wonder if there is a separate explanation for the action keys.
If so, can I change the working key?

Is it normal to always force shutdown?

For a story game, I wish I had a separate key to store.

**Comment by Baekalfen** [comment]
I think you'll need to provide some code to show what the issue is. The ESC key and the X in the window title does close PyBoy. If you program it yourself, you'll need to look for `pyboy.tick()` returning `True`

**Comment by krs013** [comment]
I'm going to close this due to inactivity. Without more information, there doesn't seem to be a bug to fix. If anything, we could say that this would be fixed by allowing remapping of the keys, and that discussion can happen in #39. If I'm wrong and there's more to say we can reopen it later, or talk on Discord.
