### ISSUE TITLE
API for rewinding

### ISSUE THREAD

**Issue by Laserlicht** [Baekalfen/PyBoy#186]
It should be possible to rewind from your own scripts. The functionality should be can controlled from "outside".

**Comment by Baekalfen** [comment]
Maybe you could give some details on what you want to use it for. We might already be the functionality you need.

**Comment by Laserlicht** [comment]
For an second chance. If you have an algorithm/network with some randomness it would be possible to give the agent an second change:
If your agent dies you can automatically rewind a few seconds and try again with new random data. Like an optimized bruteforce-method. 😃

**Comment by Baekalfen** [comment]
Enabling rewind comes at quite a big performance loss. You're probably better off brute-forcing multiple times instead.

But if you really want, you could also just save the state at certain checkpoints (like every 5 seconds), if it's solely because you want to resume from a certain point. Remember, that rewind saves the state 60 times a second.

**Comment by krs013** [comment]
I agree; save states are the way to go for scripted agents. The rewind plugin is mostly for the visual effect with interactive play. I'm going to close this, since there doesn't appear to be a need to add a feature.
