### ISSUE TITLE
Support for sound

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#28]

**Comment by a-hurst** [comment]
Just as a quick thought on this: for my own pysdl2-based project, I generate tones and noise using numpy arrays and then cast those using ctypes so that SDL2\_Mixer can play them as Mix\_Chunks using the Mix\_QuickLoadRAW function. For this case, where you want a continuous stream of sound getting played, I think you can probably bypass SDL2\_mixer (avoiding an extra dependency) and just use either a callback with SDL\_OpenAudioDevice or alternatively use SDL\_QueueAudio to avoid the need for a callback.

Either way, numpy + pysdl2 should be everything you need on the dependency end for getting audio working.

**Comment by Baekalfen** [comment]
@krs013 has been working on sound for a while. I'm not sure about the approach he took.

**Comment by krs013** [comment]
It's a bit similar to the second idea! I don't think we'll need the mixer class at all. All the audio is generated in more-or-less real time. However, I'm a strong believer in only using `numpy` when there's math to be done, and just using the `array` module otherwise, so my sample buffers reflect that.

Hopefully I'll be able to show you soon what the result looks like! I am both more and less busy this month than I was for the last few. (Though, depending on how things go with the plugin branch, I think we might want to wait until that's finished before merging sound in.)

**Comment by Baekalfen** [comment]
First version will be merged in v1.1.0
