### ISSUE TITLE
Segfault when invalid ROM path is provided

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#97]

**Comment by krs013** [comment]
This seems to be one of many bugs where a normal error becomes a segfault due to Cython optimizations. It might be a good idea to test each of these under PyPy, Cython with optimizations disabled, and Cython with optimizations enabled, and make sure the results are the same for each. Of course, the real solution is to catch these errors in runtime code instead of waiting for Python errors to do the job for us.

Other bugs I can think of are things like the divide by zero speed bug that is ignored (without consequence) in Cython, but errors out in PyPy, or the old Pokemon Gold segfault that probably was just a null pointer or OOB memory error with the previous BIOS.

**Comment by Baekalfen** [comment]
This was solved in the Docker PR
